import { chromium } from "playwright";
import { createServer } from "node:http";
import { readFileSync, existsSync } from "node:fs";
import { join, extname } from "node:path";
const DIST = "/var/home/andre/Projects/site/games.andrenijman.com/scraps/dist";
const MIME = { ".html": "text/html", ".js": "text/javascript", ".css": "text/css" };
const server = createServer((req, res) => {
  let p = join(DIST, req.url.split("?")[0] === "/" ? "index.html" : req.url.split("?")[0]);
  if (!existsSync(p)) p = join(DIST, "index.html");
  res.setHeader("content-type", MIME[extname(p)] ?? "application/octet-stream");
  res.end(readFileSync(p));
});
await new Promise((r) => server.listen(5199, r));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on("pageerror", (e) => console.log("PAGEERROR:", e.message.split("\n")[0]));
await page.goto("http://localhost:5199/", { waitUntil: "load" });
await page.waitForTimeout(2500);
await page.click("#btn-workshop");
await page.waitForTimeout(500);
await page.evaluate(() => {
  const bp = window.__dev.bp();
  const P = (def, x, y) => { const p = { id: `p${Math.random().toString(36).slice(2, 6)}`, def, x, y, rot: 0 }; bp.parts.push(p); return p; };
  const bat = P("battery_pack", 1, -1);
  const cpu = P("micro_controller", 0, 0);
  P("alu_frame", 1, 0);
  const m1 = P("motor_small", 1, 2);
  const m2 = P("motor_small", 2, 2);
  const w1 = P("wheel_medium", 1, 3);
  const w2 = P("wheel_medium", 2, 3);
  const W = (a, ap, b, bp2, kind) => bp.wires.push({ id: `w${Math.random().toString(36).slice(2, 5)}`, a: { part: a.id, port: ap }, b: { part: b.id, port: bp2 }, kind: kind ?? "power" });
  W(bat, 0, cpu, 0);
  W(bat, 0, m1, 0);
  W(m1, 1, m2, 0);
  W(m1, 2, w1, 0, "shaft");
  W(m2, 2, w2, 0, "shaft");
  const motors = [m1.id, m2.id];
  let i = 0;
  bp.python = `drive = clamp(forward() - back(), -1, 1)\nmotor("${motors[0]}", drive)\nmotor("${motors[1]}", drive)`;
  bp.logicMode = "python";
  window.__dev.setState({ logicMode: "python", python: bp.python });
});
await page.waitForTimeout(600);
await page.click("#btn-test");
await page.waitForTimeout(500);
await page.keyboard.down("KeyW");
await page.waitForTimeout(2500);
const st = await page.evaluate(() => window.__dev.state().sim.a);
await page.screenshot({ path: "shots/python-drive.png" });
console.log("python cart: x", st?.pos?.x?.toFixed(2), "charge", st?.charge + "%");
if ((st?.pos?.x ?? 0) > 16) console.log("PYTHON DRIVE OK");
else { console.log("PYTHON DRIVE FAILED"); process.exit(1); }
await browser.close(); server.close();
